### PR TITLE
Change FFmpegChapter#id type to long

### LINKED ISSUE #296: FFmpegChapter id needs to be a long
**Describe the bug**
While attempting to convert a 4k video file (about 2:20:00 in length, 31.22GB) in my spring server, the API call fails because `FFProbe` attempts to deserialize an `FFmpegProbeResult` on line 114. The `FFmpegChapter` has a field 'id' which is defined as an int, however this video file happens to have a chapterID which is larger than 32 bits. I've solved the issue for my video file by changing id to be a long.

**To Reproduce**
```java
FFmpegBuilder builder = new FFmpegBuilder();
final String inputName = "Input.mkv"
final String outputName = "output/" + inputName;
builder.setInput(inputName)     // Filename, or a FFmpegProbeResult
        .overrideOutputFiles(true) // Override the output if it exists
        .addOutput(outputName)   // Filename for the destination
        .setVideoCodec("libx265")     // Video using x264
        .setPreset("slow")
        .setConstantRateFactor(24);
final FFmpegProbeResult probe = ffprobe.probe(inputName);
```

**Expected behavior**
Expectation is that setting up the probe for the file name succeeds.

**Version (if applicable):**
 - OS: MacOS 13.4
 - Java Version 17

**Additional context**
I unfortunately am not allowed to contribute to open source projects because of my job, so I cannot create a pull request. But the fix is simple enough that it shouldn't take too much time for a contributor to fix.

### PR DESCRIPTION
**Pull request by Euklios**
This closes #296.

The data provided in the issue is sadly not complete, but using an existing file and adding the chapter information I could re-create a minimal test to accompany the fix

### CODE REVIEW

File: src/test/java/net/bramp/ffmpeg/FFprobeTest.java [hunk 1]
```diff
@@ -160,4 +163,12 @@ public void testProbeSideDataList() throws IOException {
...
     assertThat(info.getStreams().get(0).side_data_list[0].rotation, is(90));
   }
+
+  @Test
+  public void testChaptersWithLongIds() throws IOException {
+    FFmpegProbeResult info = ffprobe.probe(Samples.chapters_with_long_id);
+
+    assertThat(info.getChapters().get(0).id, is(6613449456311024506L));
+    assertThat(info.getChapters().get(1).id, is(-4433436293284298339L));
+  }
```
Comment (bramp) [inline src/test/java/net/bramp/ffmpeg/FFprobeTest.java:173]: Are chapter IDs allowed to be negative?

**Review by bramp — APPROVED** [review]
Looks great, thanks. Just one question before I merge.

File: src/test/java/net/bramp/ffmpeg/FFprobeTest.java (hunk 1 above)
Comment (Euklios) [reply src/test/java/net/bramp/ffmpeg/FFprobeTest.java:173]: Very good question, I just checked in the ffmpeg source.
They use int64_t, which is 64bit signed, so type long and negative values are supported.

I'm not sure, if ffmpeg itself will produce negative numbers, might be compatibility with other software.
